name: Purge jsDelivr cache
on:
  push:
    branches: [ main ]

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge embedded_1.js
        run: curl -s "https://purge.jsdelivr.net/gh/level2d/triptych-web@main/embedded_1.js"
      - name: Purge embedded_1.css
        run: curl -s "https://purge.jsdelivr.net/gh/level2d/triptych-web@main/embedded_1.css"
